// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ru.sggr.domain;

import org.springframework.beans.factory.annotation.Configurable;
import ru.sggr.domain.Note;

privileged aspect Note_Roo_Configurable {
    
    declare @type: Note: @Configurable;
    
}
